const readline = require("readline-sync")
console.log("")
console.log("________________________________________")
console.log("")
console.log("        COMISSÃO")
console.log("________________________________________")
console.log("")
console.log("    ~~~VENDA")
console.log("~~~")
let v = readline.questionFloat("  VALOR DA VENDA;  R$")
console.log("~~~")
console.log(" COMISSÃO DE 5%")
console.log("")
console.log("________________________________________")
console.log("")
console.log("    ~~~VALOR DA COMISSÃO; ")
console.log(`                       R$${v*0.05}`)
console.log("")
console.log("________________________________________")
console.log("")
    
