const readline = require("readline-sync")
console.log("")
console.log("________________________________________")
console.log("")
console.log("      COMANDA")
console.log("________________________________________")
console.log("")
console.log("    PEDIDO")
console.log("        ~BEBIDAS")
console.log("        ~ENTRADA")
console.log("        ~PRATOS")
console.log("        ~SOBREMESA")
console.log("        ~TAXA DE SERVIÇO 10%")
console.log("________________________________________")
console.log("")
let v = readline.questionFloat("  VALOR DO PEDIDO; R$  ")
console.log("________________________________________")
console.log("")
console.log("   TOTAL")
console.log("~~~~~")
console.log(`     R$${v+(v*0.1)}`)
console.log("")
console.log("________________________________________")
console.log("")